In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('student_placement_career_success_dataset.csv')

In [3]:
df.head(20)

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,work_mode,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,Remote,17.36,4,1,2,62,55,55,19,81
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,Onsite,18.22,3,3,0,55,66,52,54,76
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,Remote,22.08,1,3,1,79,69,67,49,34
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,Remote,20.87,2,1,2,44,44,65,61,46
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,Onsite,20.57,5,3,5,23,57,67,71,44
5,STU00006,24,Male,Uttar Pradesh,3,3,Electronics,BE,6.90,0,...,Hybrid,17.63,5,2,1,24,66,65,45,78
6,STU00007,20,Female,Karnataka,2,3,Computer Science,BE,7.66,3,...,Hybrid,23.14,2,2,5,30,78,80,52,89
7,STU00008,24,Female,Gujarat,2,3,Computer Science,MCA,5.98,0,...,Hybrid,11.43,5,3,0,5,65,40,40,57
8,STU00009,20,Male,Karnataka,2,3,Civil,BE,6.70,0,...,Onsite,20.70,1,3,4,46,66,100,62,72
9,STU00010,23,Male,Delhi,3,3,AI & DS,BTech,6.99,0,...,Hybrid,19.05,1,1,5,0,87,49,45,70
10,STU00011,21,Male,Karnataka,2,2,Information Technology,BTech,7.47,0,...,Hybrid,16.43,5,3,0,50,57,72,32,86
11,STU00012,24,Male,Telangana,1,3,Information Technology,BE,6.64,2,...,Onsite,16.96,5,1,5,73,40,72,66,38
12,STU00013,20,Male,Gujarat,2,2,AI & DS,MCA,8.31,0,...,Onsite,21.40,2,1,5,32,35,32,44,51
13,STU00014,22,Male,Tamil Nadu,3,3,Civil,MCA,6.22,2,...,Hybrid,16.28,1,1,4,21,93,83,44,87
14,STU00015,23,Female,Uttar Pradesh,1,1,Electronics,MCA,9.90,1,...,Onsite,25.14,3,1,3,19,50,57,14,76
15,STU00016,22,Male,Telangana,3,3,Computer Science,BTech,7.15,1,...,Hybrid,17.87,4,1,4,15,94,70,80,59
16,STU00017,24,Male,Gujarat,3,3,Computer Science,BTech,7.77,0,...,Remote,22.17,4,1,1,40,60,59,79,72
17,STU00018,25,Female,West Bengal,3,3,Mechanical,MCA,6.26,0,...,Hybrid,14.70,3,3,3,34,56,58,21,69
18,STU00019,25,Female,Tamil Nadu,1,1,Information Technology,MCA,8.83,2,...,Onsite,19.83,4,1,4,34,62,55,55,60
19,STU00020,23,Female,Uttar Pradesh,1,3,Civil,BE,8.18,0,...,Remote,18.11,2,2,3,42,79,57,38,85

In [4]:
df.shape

(25000, 44)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  25000 non-null  object
 1   age                         25000 non-null  int64
 2   gender                      25000 non-null  object
 3   state                       25000 non-null  object
 4   city_tier                   25000 non-null  int64
 5   college_tier                25000 non-null  int64
 6   branch                      25000 non-null  object
 7   degree                      25000 non-null  object
 8   cgpa                        25000 non-null  float64
 9   backlog_history             25000 non-null  int64
 10  attendance_percentage       25000 non-null  float64
 11  primary_language            25000 non-null  object
 12  DSA_problems_solved         25000 non-null  int64
 13  GitHub_repos                24500 non-null  float64
 14  hackathons_participated     25000 non-null  int64
 15  development_projects_count  25000 non-null  int64
 16  AI_ML_projects              25000 non-null  int64
 17  internships_completed       25000 non-null  int64
 18  resume_score                25000 non-null  int64
 19  communication_skills        25000 non-null  int64
 20  aptitude_score              25000 non-null  int64
 21  mock_interview_score        24500 non-null  float64
 22  sleep_hours                 24500 non-null  float64
 23  screen_time                 25000 non-null  float64
 24  gaming_hours                25000 non-null  float64
 25  study_hours_daily           25000 non-null  float64
 26  stress_level                25000 non-null  int64
 27  burnout_score               25000 non-null  int64
 28  gym_frequency               25000 non-null  int64
 29  family_income_lpa           25000 non-null  float64
 30  self_learning_hours         25000 non-null  float64
 31  motivation_level            25000 non-null  int64
 32  placement_status            25000 non-null  object
 33  company_type                24596 non-null  object
 34  work_mode                   24596 non-null  object
 35  salary_lpa                  25000 non-null  float64
 36  interview_rounds_cleared    25000 non-null  int64
 37  offer_count                 25000 non-null  int64
 38  joining_delay_months        25000 non-null  int64
 39  layoffs_risk_score          25000 non-null  int64
 40  AI_tool_usage_frequency     25000 non-null  int64
 41  prompt_engineering_skill    25000 non-null  int64
 42  AI_fear_score               25000 non-null  int64
 43  adaptability_score          25000 non-null  int64
dtypes: float64(11), int64(24), object(9)
memory usage: 8.4+ MB

In [6]:
df.describe()

,age,city_tier,college_tier,cgpa,backlog_history,attendance_percentage,DSA_problems_solved,GitHub_repos,hackathons_participated,development_projects_count,...,motivation_level,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,24500.000000,25000.000000,25000.000000,...,25000.0000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,22.507520,2.104360,2.354160,7.460975,0.468040,77.942360,646.777800,18.688490,2.612720,6.396520,...,69.3320,19.006936,2.972560,1.967400,2.45592,34.786640,59.333080,60.375200,44.549720,64.460400
std,1.706898,0.768201,0.726217,0.846094,0.810262,9.956108,124.989386,9.219579,1.835709,2.631921,...,14.7297,4.244388,1.445811,0.845107,1.71551,15.110894,19.396358,16.647395,19.782843,14.944899
min,20.000000,1.000000,1.000000,5.000000,0.000000,45.000000,185.000000,0.000000,0.000000,1.000000,...,5.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,21.000000,2.000000,2.000000,6.890000,0.000000,71.200000,562.000000,12.000000,1.000000,5.000000,...,59.0000,16.750000,2.000000,1.000000,1.00000,24.000000,46.000000,49.000000,31.000000,54.000000
50%,22.000000,2.000000,3.000000,7.460000,0.000000,78.000000,646.000000,18.000000,3.000000,6.000000,...,70.0000,19.130000,3.000000,2.000000,2.00000,35.000000,60.000000,60.000000,45.000000,64.000000
75%,24.000000,3.000000,3.000000,8.030000,1.000000,84.900000,731.000000,25.000000,4.000000,8.000000,...,80.0000,21.570000,4.000000,3.000000,4.00000,45.000000,73.000000,72.000000,58.000000,75.000000
max,25.000000,3.000000,3.000000,10.000000,3.000000,100.000000,1163.000000,60.000000,10.000000,18.000000,...,100.0000,35.100000,5.000000,3.000000,5.00000,100.000000,100.000000,100.000000,100.000000,100.000000

In [7]:
df.columns

Index(['student_id', 'age', 'gender', 'state', 'city_tier', 'college_tier',
       'branch', 'degree', 'cgpa', 'backlog_history', 'attendance_percentage',
       'primary_language', 'DSA_problems_solved', 'GitHub_repos',
       'hackathons_participated', 'development_projects_count',
       'AI_ML_projects', 'internships_completed', 'resume_score',
       'communication_skills', 'aptitude_score', 'mock_interview_score',
       'sleep_hours', 'screen_time', 'gaming_hours', 'study_hours_daily',
       'stress_level', 'burnout_score', 'gym_frequency', 'family_income_lpa',
       'self_learning_hours', 'motivation_level', 'placement_status',
       'company_type', 'work_mode', 'salary_lpa', 'interview_rounds_cleared',
       'offer_count', 'joining_delay_months', 'layoffs_risk_score',
       'AI_tool_usage_frequency', 'prompt_engineering_skill', 'AI_fear_score',
       'adaptability_score'],
      dtype='object')

In [8]:
print(df['mock_interview_score'].head(10))

0      NaN
1     80.0
2     81.0
3    100.0
4     68.0
5     70.0
6     72.0
7     96.0
8     77.0
9     83.0
Name: mock_interview_score, dtype: float64

In [9]:
#How many students are Placed vs Not Placed? Show the count

df['placement_status'].value_counts()

placement_status
Placed        24596
Not Placed      404
Name: count, dtype: int64

In [10]:
#Which columns have missing values? How many nulls in each?
df.isna().sum()

student_id                      0
age                             0
gender                          0
state                           0
city_tier                       0
college_tier                    0
branch                          0
degree                          0
cgpa                            0
backlog_history                 0
attendance_percentage           0
primary_language                0
DSA_problems_solved             0
GitHub_repos                  500
hackathons_participated         0
development_projects_count      0
AI_ML_projects                  0
internships_completed           0
resume_score                    0
communication_skills            0
aptitude_score                  0
mock_interview_score          500
sleep_hours                   500
screen_time                     0
gaming_hours                    0
study_hours_daily               0
stress_level                    0
burnout_score                   0
gym_frequency                   0
family_income_lpa               0
self_learning_hours             0
motivation_level                0
placement_status                0
company_type                  404
work_mode                     404
salary_lpa                      0
interview_rounds_cleared        0
offer_count                     0
joining_delay_months            0
layoffs_risk_score              0
AI_tool_usage_frequency         0
prompt_engineering_skill        0
AI_fear_score                   0
adaptability_score              0
dtype: int64

In [11]:
#What is the average CGPA of all students?
df['cgpa'].mean()

np.float64(7.4609752)

In [12]:
#List all unique branches in the dataset.
df['branch'].unique()

array(['Computer Science', 'AI & DS', 'Civil', 'Electronics',
       'Information Technology', 'Mechanical'], dtype=object)

In [13]:
#What is the average salary (salary_lpa) for each company type?

a = df.groupby('company_type')['salary_lpa'].mean()
a

company_type
MNC              19.287854
Product-Based    19.362896
Service-Based    19.340988
Startup          19.285312
Name: salary_lpa, dtype: float64

In [14]:
#Filter students who have more than 5 AI/ML projects and are Placed. How many are there?

df[(df['AI_ML_projects']>5) & (df['placement_status'] == 'Placed')]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,work_mode,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
8,STU00009,20,Male,Karnataka,2,3,Civil,BE,6.70,0,...,Onsite,20.70,1,3,4,46,66,100,62,72
26,STU00027,23,Female,Karnataka,3,2,AI & DS,BE,7.22,0,...,Remote,22.71,3,2,0,29,66,84,56,71
64,STU00065,23,Female,West Bengal,1,3,Civil,MCA,6.72,0,...,Remote,19.70,1,3,1,58,43,81,53,86
72,STU00073,21,Male,Delhi,1,2,Information Technology,BE,7.96,1,...,Remote,26.91,1,3,3,40,81,68,18,61
76,STU00077,22,Male,Gujarat,3,1,Computer Science,BTech,8.97,0,...,Hybrid,28.08,1,3,0,44,33,87,53,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24899,STU24900,24,Female,Uttar Pradesh,3,3,Information Technology,BE,6.59,0,...,Onsite,19.59,2,1,4,22,22,68,19,70
24908,STU24909,23,Female,Maharashtra,3,1,Civil,BTech,8.27,0,...,Onsite,27.58,1,1,3,44,28,83,30,70
24953,STU24954,22,Female,Tamil Nadu,1,2,Information Technology,BTech,7.81,0,...,Onsite,20.23,5,1,1,48,69,77,34,77
24967,STU24968,20,Male,Karnataka,3,3,Civil,BTech,9.75,0,...,Onsite,29.52,1,1,1,31,46,65,35,84
24973,STU24974,23,Male,Delhi,3,2,Mechanical,BE,6.52,0,...,Hybrid,16.14,2,1,4,30,48,58,71,49

In [15]:
#Which branch has the highest placement rate (% of students placed)?
b = df.groupby('placement_status')['branch']
for i,v in b:
    if i == 'Placed':
        placed = v.value_counts()
        print(placed)

branch
Mechanical                4186
Computer Science          4140
AI & DS                   4107
Information Technology    4101
Civil                     4091
Electronics               3971
Name: count, dtype: int64

In [16]:
#placed = df[df['placement_status'] == 'Placed'].groupby('branch')['student_id'].count()
#print(placed)

In [17]:
total = df.groupby('branch')['student_id'].count()
print(total)

branch
AI & DS                   4182
Civil                     4151
Computer Science          4203
Electronics               4053
Information Technology    4166
Mechanical                4245
Name: student_id, dtype: int64

In [18]:
rate = (placed / total) * 100
print(rate)

branch
AI & DS                   98.206600
Civil                     98.554565
Computer Science          98.501071
Electronics               97.976807
Information Technology    98.439750
Mechanical                98.610130
dtype: float64

In [19]:
rate.sort_values(ascending=False)
print(rate.idxmax())

Mechanical

In [20]:
print(df['mock_interview_score'].isnull().sum())
print(df['GitHub_repos'].isnull().sum())

500
500

In [21]:
#Fill missing values in GitHub_repos and mock_interview_score with their median. Confirm no nulls remain.

df['GitHub_repos'] = df['GitHub_repos'].fillna(df['GitHub_repos'].median())
#df['mock_interview_score'] = pd.to_numeric(df['mock_interview_score'],errors='coerce')
df['mock_interview_score'] = df['mock_interview_score'].fillna(df['mock_interview_score'].median())

In [22]:
print(df['mock_interview_score'].isnull().sum())
print(df['GitHub_repos'].isnull().sum())

0
0

In [23]:
#Find the 25th, 50th, and 75th percentile of salary_lpa using NumPy.
np.percentile(df['salary_lpa'].dropna(),[25,50,75])

array([16.75, 19.13, 21.57])

In [24]:
#Create a new column high_cgpa: 1 if cgpa > 8, else 0. Use np.where()
df [ 'high_cgpa'] = np.where(df['cgpa'] > 8,1,0)

In [27]:
df

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,17.36,4,1,2,62,55,55,19,81,0
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,18.22,3,3,0,55,66,52,54,76,0
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,20.87,2,1,2,44,44,65,61,46,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24997,STU24998,24,Male,Karnataka,2,3,Mechanical,MCA,7.34,0,...,20.22,4,1,4,17,43,72,24,87,0
24998,STU24999,20,Male,Delhi,2,2,Information Technology,BTech,7.59,1,...,19.79,2,2,3,49,93,53,59,77,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [28]:
df['high_cgpa'].head(20)

0     0
1     0
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    1
13    0
14    1
15    0
16    0
17    0
18    1
19    1
Name: high_cgpa, dtype: int64

In [29]:
#Compare average prompt_engineering_skill between Placed and Not Placed students.
df['prompt_engineering_skill'].groupby(df['placement_status']).mean()

placement_status
Not Placed    56.014851
Placed        60.446821
Name: prompt_engineering_skill, dtype: float64

In [30]:
#Find which 3 numeric columns have the strongest correlation with salary_lpa.

df.corr(numeric_only=True)['salary_lpa'].sort_values(ascending=False).head(4)

salary_lpa                    1.000000
internships_completed         0.541650
development_projects_count    0.507059
cgpa                          0.494012
Name: salary_lpa, dtype: float64

In [36]:
#Filter students with AI_ML_projects > 2 AND Placed — what's their average salary?

result = df[(df['AI_ML_projects']>2) & (df['placement_status'] == 'Placed')] 
print(result['salary_lpa'].mean())

20.618443109218134

In [38]:
#Make a pivot table: average salary by branch and work_mode.
pd.pivot_table(df,
              values='salary_lpa',
              index='branch',
              columns='work_mode',
              aggfunc='mean')

work_mode                  Hybrid     Onsite     Remote
branch
AI & DS                 19.226337  19.234127  19.281594
Civil                   19.489316  19.383361  19.245660
Computer Science        19.261308  19.287193  19.303727
Electronics             19.343064  19.280933  19.358818
Information Technology  19.330198  19.213897  19.419282
Mechanical              19.343879  19.308190  19.424401

In [49]:
 #Among placed students from Tier 1 colleges, what is the average AI_tool_usage_frequency vs Tier 2 and Tier 3?
placed = df[df['placement_status'] == 'Placed']
placed.groupby('college_tier')['AI_tool_usage_frequency'].mean()

college_tier
1    59.809793
2    59.146863
3    59.284334
Name: AI_tool_usage_frequency, dtype: float64